name: CI on Push

on:
  push:
    branches:
      - main # Trigger this workflow only on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Git configuration
      - name: Configure Git
        run: |
          git config --global user.name "Your GitHub Username"
          git config --global user.email "your-email@example.com"

      

      # Step 3: Run a simple script (optional)
      - name: Run a script
        run: |
          echo "Hello, world!"
          echo "The code has been pushed to the repository!"
